Repository 95LeeDuo/moanda-ve, pull requests merged in 2024-04, with the labels that each got.

#32 인스타그램 API 구현
  src/apis/axios.ts
  src/apis/instagram.ts
  src/components/Intro/LogoDescription/index.tsx
  src/components/Menu/MenuDetail/index.tsx
Labels: 💫 feat, 🟦 typescript

#33 인스타그램 게시물 불러오기
  package.json
  public/loading.gif
  src/App.css
  src/App.tsx
  src/apis/axios.ts
  src/apis/instagram.ts
  src/components/Common/Header/style.ts
  src/components/Common/LoadingUI/index.tsx
  src/components/Common/ReactQueryProvider.tsx
  src/components/Gallery/InstaItem/index.tsx
  src/components/Gallery/InstaItem/style.ts
  src/components/Gallery/InstaList/index.tsx
  src/components/Gallery/InstaList/style.ts
  src/components/Gallery/InstaModal/index.tsx
  src/components/Gallery/InstaModal/style.ts
  src/pages/Gallery/index.tsx
  src/pages/Gallery/style.ts
  src/styles/theme.ts
  src/types/insta.ts
  src/utils/parseData.ts
  yarn.lock
Labels: ⚙️ chore, 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#34 메인 이미지 및 메인인스타 추가
  public/Intro/intro-img.png
  public/Intro/intro-logo.png
  public/Main/intro2.png
  public/Outside/outside_5.jpg
  public/Outside/outside_7_1.jpg
  src/apis/instagram.ts
  src/components/Gallery/InstaList/index.tsx
  src/components/Home/Intro/index.tsx
  src/components/Home/Intro/style.ts
  src/components/Home/PreviewInsta/index.tsx
  src/components/Home/PreviewInsta/style.ts
  src/components/Intro/LogoDescription/index.tsx
Labels: 📝 docs, 🧑🏻‍🎨 UI

#35 갤러리 페이지에 블로그 리뷰 추가
  public/Blog/또니.jpg
  public/Blog/옥블리.jpg
  public/Blog/이다콩.jpg
  src/components/Gallery/BlogItem/index.tsx
  src/components/Gallery/BlogItem/style.ts
  src/components/Gallery/BlogList/index.tsx
  src/components/Gallery/BlogList/style.ts
  src/components/Gallery/InstaList/style.ts
  src/components/Gallery/InstaModal/style.ts
  src/constants/Blogs.json
  src/pages/Gallery/index.tsx
  src/types/blog.ts
Labels: 📝 docs, 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#36 swiper 사이즈 조절 및 NewProduct 주석
  public/Intro/intro-logo.png
  public/poster.png
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/components/Home/Intro/index.tsx
  src/components/Home/Intro/style.ts
  src/components/Intro/IntroHeader/style.ts
  src/pages/Home/index.tsx
Labels: 📝 docs, 🧑🏻‍🎨 UI

#38 메인페이지 답례품 미리보기 컴포넌트 구현
  index.html
  public/Intro/inside_1.jpg
  public/Intro/inside_2.jpg
  public/Intro/inside_3.jpg
  public/Intro/inside_4.jpg
  public/Intro/inside_5.jpg
  public/Main/Gift/종이봉투.jpg
  public/gift/6/종이봉투.jpg
  public/robots.txt
  public/sitemap.xml
  public/vite.svg
  robots.txt
  sitemap.xml
  src/components/Common/Swiper/index.tsx
  src/components/Gallery/InstaItem/style.ts
  src/components/Gallery/InstaList/style.ts
  src/components/Gallery/InstaModal/index.tsx
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/components/Home/NewProduct/index.tsx
  src/components/Home/NewProduct/style.ts
  src/components/Home/PreviewGift/index.tsx
  src/components/Home/PreviewGift/style.ts
  src/components/Home/PreviewInsta/style.ts
  src/components/Intro/LogoDescription/style.ts
  src/components/Intro/VeganDescription/index.tsx
  src/components/Intro/VeganDescription/style.ts
  src/components/Menu/MenuDetail/style.ts
  src/constants/IntroGift.json
  src/font/Adultkid.ttf
  src/font/font.css
  src/pages/Home/index.tsx
  src/types/swiper.ts
Labels: 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#39 갤러리 info 내용 추가
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/components/Home/PreviewGift/style.ts
  src/components/Intro/VeganDescription/index.tsx
Labels: 📝 docs, 🧑🏻‍🎨 UI

#40 사소한 디자인 수정
  src/components/Gallery/InstaModal/style.ts
  src/components/Home/PreviewGift/style.ts
Labels: 🧑🏻‍🎨 UI

#41 답례품 페이지 Contact 추가 및 info json 정리
  src/components/Gallery/InstaModal/style.ts
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/constants/GiftData.json
Labels: 📝 docs, 🧑🏻‍🎨 UI

#42 답례품 미리보기 컴포넌트 구현
  index.html
  public/Main/Gift/연노랑박스.jpg
  public/Main/Gift/왕리본도시락박스.jpg
  public/Main/Gift/종이봉투.jpg
  public/Main/Gift/친환경사각박스.jpg
  public/Main/Gift/크라프트사각박스.jpg
  src/components/Common/Swiper/index.tsx
  src/components/Gallery/InstaModal/style.ts
  src/components/Home/PreviewGift/index.tsx
  src/components/Home/PreviewGift/style.ts
  src/components/Home/PreviewInsta/style.ts
  src/components/Intro/WayToCome/style.ts
  src/stores/swiperCurrentIndexStore.ts
Labels: 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#43 사이즈 에러 수정
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
Labels: 🧑🏻‍🎨 UI

#44 답례품 미리보기 컴포넌트 디자인 수정
  src/components/Home/Intro/index.tsx
  src/components/Home/PreviewGift/index.tsx
  src/components/Home/PreviewGift/style.ts
Labels: 🧑🏻‍🎨 UI

#45 이미지 변경
  public/gift/poster.png
  public/gift/친환경사각/쇼핑백포장 예시.jpg
  public/gift/친환경사각/쿠키3종+휘낭4종.jpg
  public/gift/친환경사각/쿠키6종.jpg
  public/gift/친환경사각/휘낭8종.jpg
  public/gift/크라프트사각/박스 예시.jpg
  public/gift/크라프트사각/박스 예시2.jpg
  public/gift/크라프트사각/박스 예시3.jpg
  public/gift/크라프트사각/박스 예시4.jpg
  public/gift/크라프트사각/쿠키10종.jpg
  public/gift/크라프트사각/쿠키6종+휘낭6종.jpg
  public/gift/크라프트사각/휘낭14종.jpg
Labels: 📝 docs

#46 이미지 해상도 테스트
  public/gift/5/쿠키 6종 + 휘낭시에 6종.jpg
  public/gift/_poster.png
  public/gift/poster.png
  public/gift/도시락/기본 도시락박스 .jpg
  public/gift/도시락/기본 도시락박스.jpg
  public/gift/도시락/왕리본 도시락박스 .jpg
  public/gift/도시락/왕리본 도시락박스.jpg
  public/gift/도시락/쿠키1종_휘낭시에2종.jpg
  public/gift/도시락/쿠키2종.jpg
  public/gift/도시락/쿠키3종.jpg
  public/gift/도시락/휘낭시에 4종.jpg
  public/gift/연노랑미니/결혼 답례품.jpg
  public/gift/연노랑미니/기업 답례품.jpg
  public/gift/연노랑미니/미니쿠키2종.jpg
  public/gift/연노랑미니/미니쿠키3종.jpg
  public/gift/연노랑미니/연노랑박스.jpg
  public/gift/연노랑미니/청첩장모임 답례품.jpg
  public/gift/연노랑미니/퇴임 답례품.jpg
  public/gift/연노랑미니/휘낭2종.jpg
  public/gift/친환경사각/쿠키3종_휘낭4종.jpg
  public/gift/친환경직사각/3) 쿠키2종+휘낭2종 사진.jpg
  public/gift/친환경직사각/친환경 직사각박스  .jpg
  public/gift/친환경직사각/친환경 직사각박스 .jpg
  public/gift/친환경직사각/친환경 직사각박스.jpg
  public/gift/친환경직사각/쿠키2종_휘낭2종.jpg
  public/gift/친환경직사각/쿠키4종.jpg
  public/gift/친환경직사각/휘낭시에5종.jpg
  public/gift/크라프트사각/쿠키6종_휘낭6종.jpg
  public/gift/크라프트사각/크라프트 사각박스   .jpg
  public/gift/크라프트사각/크라프트 사각박스  .jpg
  public/gift/크라프트사각/크라프트 사각박스 .jpg
  public/gift/크라프트사각/크라프트 사각박스.jpg
  public/menu/bottleCake/blackSesame.jpg
  public/menu/bottleCake/chocoFruit.jpg
  public/menu/bottleCake/chocoMatcha.jpg
  public/menu/bottleCake/chocoStrawberry.jpg
  public/menu/bottleCake/mugwortInjeolmi.jpg
  public/menu/bottleCake/보틀케이크.jpg
  public/menu/bottleCake/쑥절미.jpg
  public/menu/bottleCake/초코과일.jpg
  public/menu/bottleCake/초코말차.jpg
  public/menu/bottleCake/흑임자.jpg
  src/App.css
  src/components/Gift/GiftForm/index.tsx
  src/components/Gift/GiftForm/style.ts
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/components/Home/Intro/index.tsx
  src/components/Menu/MenuModal/index.tsx
  src/components/Menu/MenuModal/style.ts
  src/constants/GiftData.json
  src/constants/MenuData.json
Labels: ⚙️ chore

#47 이미지 변경
  public/gift/_poster.png
  src/components/Gift/GiftForm/style.ts
Labels: 📝 docs

#48 readme 수정
  README.md
Labels: 📝 docs

#50 디자인 에러 수정
  public/Intro/outside_9.jpg
  public/gift/친환경사각/리본 사각박스.jpg
  public/gift/친환경사각/쇼핑백포장 예시.jpg
  public/gift/친환경사각/친환경 사각박스 .jpg
  public/gift/친환경사각/친환경 사각박스.jpg
  public/gift/친환경사각/합격기원 답례품.jpg
  public/gift/크라프트사각/쿠키6종_휘낭6종.jpg
  src/components/Gallery/InstaItem/index.tsx
  src/components/Gallery/InstaModal/index.tsx
  src/components/Gift/GiftItemList/index.tsx
  src/components/Gift/GiftItemList/style.ts
  src/components/Home/Intro/index.tsx
  src/components/Home/PreviewInsta/style.ts
  src/components/Intro/VeganDescription/index.tsx
  src/constants/GiftData.json
Labels: 🐛 bug

#51 ios 오류 수정
  src/components/Home/PreviewInsta/style.ts
  src/components/Intro/LocationCard/index.tsx
  src/components/Intro/LocationCard/style.ts
  src/components/Intro/WayToCome/index.tsx
Labels: 🐛 bug

#52 vercel analytics 추가 및 인스타그램 브라우저 오류 수정
  package.json
  src/components/Common/Header/style.ts
  src/components/Home/Intro/style.ts
  src/components/Home/PreviewGift/style.ts
  src/main.tsx
  yarn.lock
Labels: 🐛 bug
