Repository 95LeeDuo/moanda-ve, pull requests merged in 2024-01, with the labels that each got.

#8 헤더 & 스와이퍼 & 테마 구현 및 Vercel 설정
  .gitignore
  package.json
  public/Logo/Logo.jpg
  public/Mobile/Main/img_1.jpg
  public/Mobile/Main/img_10.jpg
  public/Mobile/Main/img_11.jpg
  public/Mobile/Main/img_12.jpg
  public/Mobile/Main/img_2.jpg
  public/Mobile/Main/img_3.jpg
  public/Mobile/Main/img_4.jpg
  public/Mobile/Main/img_5.jpg
  public/Mobile/Main/img_6.jpg
  public/Mobile/Main/img_7.jpg
  public/Mobile/Main/img_8.jpg
  public/Mobile/Main/img_9.jpg
  src/App.css
  src/App.tsx
  src/components/HamburgerMenu/index.tsx
  src/components/HamburgerMenu/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Layout/index.tsx
  src/components/Layout/style.ts
  src/components/Swiper/index.tsx
  src/components/Swiper/style.ts
  src/index.css
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Home/index.tsx
  src/pages/Intro/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/style.ts
  src/routes/Router.tsx
  src/styles/theme.ts
  src/types/styled-components.d.ts
  src/util/importImage.ts
  vercel.json
  yarn.lock
Labels: ⚙️ chore, 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#10 메뉴소개 메뉴 컴포넌트 구현 진행
  public/menu/cookie_1.jfif
  public/menu/cookie_2.jfif
  public/menu/cookie_3.jfif
  public/menu/cookie_4.jfif
  public/menu/cookie_5.jfif
  public/menu/cookie_6.jfif
  public/menu/cookie_7.jfif
  public/menu/finan_1.jfif
  public/menu/finan_2.jfif
  public/menu/finan_3.jfif
  public/menu/finan_4.jfif
  public/menu/finan_5.jfif
  public/menu/finan_6.jfif
  src/App.css
  src/components/MenuDetail/index.tsx
  src/components/MenuDetail/style.ts
  src/components/MenuModal/index.tsx
  src/components/MenuModal/style.ts
  src/pages/Gallery/index.tsx
  src/pages/Gallery/style.ts
  src/pages/Intro/index.tsx
  src/pages/Intro/style.ts
  src/pages/Menu/index.tsx
  src/pages/Menu/style.ts
  src/pages/Notice/index.tsx
  src/pages/Notice/style.ts
  src/routes/Router.tsx
  src/util/MenuData.ts
Labels: 📝 docs, 💫 feat, 🟦 typescript, 🧑🏻‍🎨 UI

#16 모달 디자인 및 메뉴 데이터 수정
  src/components/MenuDetail/index.tsx
  src/components/MenuModal/index.tsx
  src/components/MenuModal/style.ts
  src/constants/MenuData.json
  src/util/MenuData.json
Labels: 📝 docs, 💫 feat, 🧑🏻‍🎨 UI

#17 카페소개 페이지의 로고 소개 컴포넌트 구현
  src/components/Common/IntroHeader/index.tsx
  src/components/Common/IntroHeader/style.ts
  src/components/LogoDescription/index.tsx
  src/components/LogoDescription/style.ts
  src/components/MenuModal/style.ts
  src/components/Swiper/index.tsx
  src/components/WayToCome/index.tsx
  src/components/WayToCome/style.ts
  src/pages/Intro/index.tsx
Labels: 💫 feat, 🧑🏻‍🎨 UI

#18 비건 소개 컴포넌트 구현 및 카페소개 페이지 스크롤 애니메이션 구현
  index.html
  public/favicon.png
  src/components/Footer/index.tsx
  src/components/Footer/style.ts
  src/components/LogoDescription/style.ts
  src/components/VeganDescription/index.tsx
  src/components/VeganDescription/style.ts
  src/components/WayToCome/index.tsx
  src/components/WayToCome/style.ts
  src/constants/intro.json
  src/pages/Intro/index.tsx
  src/pages/Intro/style.ts
Labels: 💫 feat, 🧑🏻‍🎨 UI

#19 메뉴 데이터 수정 및 추가
  public/menu/cookie_appleCinnamon.jfif
  public/menu/cookie_earlGray.jfif
  public/menu/cookie_lamington.jfif
  public/menu/cookie_lottus.jfif
  public/menu/cookie_oreo.jfif
  public/menu/cookie_peanutberry.jfif
  public/menu/cookie_plain.jfif
  public/menu/finan_6.jfif
  public/menu/finan_caramelPecan.jfif
  public/menu/finan_caramelSalt.jfif
  public/menu/finan_saltChoco.jfif
  public/menu/finan_sweetPotato.jfif
  public/menu/finan_vanilla.jfif
  public/menu/finan_walnut.jfif
  src/constants/MenuData.json
Labels: 📝 docs
