Repository 95LeeDuo/moanda-ve, pull requests merged in 2024-02, with the labels that each got.

#20 메뉴데이터 추가 및 배민컴포넌트 제작 중
  public/Logo/baemin.png
  public/menu/biscotti/chocoChip.jpg
  public/menu/biscotti/cranBerry.jpg
  public/menu/bottleCake/blackSesame.jpg
  public/menu/bottleCake/chocoFruit.jpg
  public/menu/bottleCake/chocoMatcha.jpg
  public/menu/bottleCake/chocoStrawberry.jpg
  public/menu/bottleCake/mugwortInjeolmi.jpg
  public/menu/pound/carrotPecan.jpg
  public/menu/pound/figEarlgray.jpg
  src/components/Baemin/index.tsx
  src/components/Baemin/style.ts
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/LocationCard/style.ts
  src/components/Swiper/index.tsx
  src/components/WayToCome/style.ts
  src/constants/MenuData.json
  src/constants/base.json
  src/constants/importImage.ts
  src/pages/Intro/index.tsx
Labels: 📝 docs, 💫 feat, 🧑🏻‍🎨 UI

#21 메뉴 데이터 수정
  public/menu/cookie/appleCinnamon.jpg
  public/menu/cookie/earlGrayLemon.jpg
  public/menu/cookie/ferrero.jpg
  public/menu/cookie/flowerRiceCake.jpg
  public/menu/cookie/lamington.jpg
  public/menu/cookie/lotus.jpg
  public/menu/cookie/matchaShu.jpg
  public/menu/cookie/oreo.jpg
  public/menu/cookie/peanutBerry.jpg
  public/menu/cookie/plane.jpg
  public/menu/cookie_4.jfif
  public/menu/cookie_6.jfif
  public/menu/cookie_7.jfif
  public/menu/cookie_appleCinnamon.jfif
  public/menu/cookie_earlGray.jfif
  public/menu/cookie_lamington.jfif
  public/menu/cookie_lottus.jfif
  public/menu/cookie_oreo.jfif
  public/menu/cookie_peanutberry.jfif
  public/menu/cookie_plain.jfif
  public/menu/finan/blueberry.jpg
  public/menu/finan/caramelSalt.jpg
  public/menu/finan/earlGrayChoco.jpg
  public/menu/finan/ferrero.jpg
  public/menu/finan/lamington.jpg
  public/menu/finan/lemon.jpg
  public/menu/finan/matchaChoco.jpg
  public/menu/finan/pecanCaramel.jpg
  public/menu/finan/saltChoco.jpg
  public/menu/finan/sweetPotato.jpg
  public/menu/finan/sweetPumpkinRiceCake.jpg
  public/menu/finan/vanilla.jpg
  public/menu/finan/walnut.jpg
  public/menu/finan_caramelPecan.jfif
  public/menu/finan_caramelSalt.jfif
  public/menu/finan_saltChoco.jfif
  public/menu/finan_sweetPotato.jfif
  public/menu/finan_vanilla.jfif
  public/menu/finan_walnut.jfif
  public/menu/wholeCake/bottle4Cake.jpg
  public/menu/wholeCake/miniChocoFruitCake.jpg
  public/menu/wholeCake/no1ChocoFruitCake.jpg
  src/components/MenuDetail/index.tsx
  src/components/MenuModal/index.tsx
  src/components/MenuModal/style.ts
  src/constants/MenuData.json
  src/constants/base.json
Labels: 📝 docs, 🧑🏻‍🎨 UI

#22 메뉴 모달 버그 수정
  src/components/MenuDetail/index.tsx
  src/components/MenuDetail/style.ts
  src/components/MenuModal/index.tsx
  src/components/MenuModal/style.ts
  src/constants/MenuData.json
Labels: 💫 feat, 🧑🏻‍🎨 UI

#23 애니메이션 수정
  src/components/MenuDetail/index.tsx
  src/components/MenuDetail/style.ts
Labels: 🧑🏻‍🎨 UI

#24 메뉴 데이터 수정
  src/constants/MenuData.json
Labels: 📝 docs

#25 답례품 페이지 추가
  public/gift/1/결혼답례품.jpg
  public/gift/1/기업답례품.jpg
  public/gift/1/미니쿠키2종.jpg
  public/gift/1/미니쿠키3종.jpg
  public/gift/1/연노랑박스.jpg
  public/gift/1/청첩장모임답례품.jpg
  public/gift/1/퇴임답례품.jpg
  public/gift/1/휘낭2종.jpg
  public/gift/2/기본도시락박스포장.jpg
  public/gift/2/기본도시락박스포장2.jpg
  public/gift/2/왕리본도시락박스포장.jpg
  public/gift/2/왕리본도시락박스포장2.jpg
  public/gift/2/쿠키1종+휘낭시에2종.jpg
  public/gift/2/쿠키2종.jpg
  public/gift/2/쿠키3종.jpg
  public/gift/2/휘낭시에 4종.jpg
  public/gift/3/쿠키2종+휘낭2종.jpg
  public/gift/3/쿠키2종+휘낭2종2.jpg
  public/gift/3/쿠키4종.jpg
  public/gift/3/휘낭시에5종.jpg
  public/gift/4/쇼핑백포장 예시.jpg
  public/gift/4/쿠키3종+휘낭3종.jpg
  public/gift/4/쿠키6종.jpg
  public/gift/4/휘낭8종선물세트.jpg
  public/gift/5/쿠키10종 + 휘낭시에10종.jpg
  public/gift/5/쿠키10종.jpg
  public/gift/5/휘낭14종.jpg
  public/gift/5/휘낭5종+음료.jpg
  public/gift/6/KakaoTalk_20240223_171118221.jpg
  public/gift/6/KakaoTalk_20240223_171628045_04.jpg
  public/gift/6/KakaoTalk_20240223_181608729_01.jpg
  public/gift/6/KakaoTalk_20240223_181608729_10.jpg
  public/gift/6/KakaoTalk_20240223_181810831.jpg
  public/gift/6/KakaoTalk_20240223_181810831_01.jpg
  public/poster.png
  src/components/GiftForm/index.tsx
  src/components/GiftForm/style.ts
  src/components/GiftItemList/index.tsx
  src/components/GiftItemList/style.ts
  src/components/MenuDetail/index.tsx
  src/constants/GiftData.json
  src/pages/Gift/index.tsx
  src/pages/Gift/style.ts
Labels: 📝 docs, 🧑🏻‍🎨 UI

#26 메인페이지 구현 중
  .gitignore
  public/Icon/gift.png
  public/Icon/main.png
  public/Icon/main512.png
  public/Icon/newProduct.png
  public/Logo/baemin_des.png
  public/Main/Gift/연노랑박스.jpg
  public/Main/Gift/왕리본도시락박스.jpg
  public/Main/Gift/종이봉투.jpg
  public/Main/Gift/친환경사각박스.jpg
  public/Main/Gift/크라프트사각박스.jpg
  public/Mobile/Main/img_6.jpg
  public/test.jfif
  public/test.jpg
  public/test2.jfif
  public/test2.jpg
  public/test3.jpg
  src/App.css
  src/components/Baemin/index.tsx
  src/components/Common/FullPageScroll/index.tsx
  src/components/Common/FullPageScroll/style.ts
  src/components/Footer/style.ts
  src/components/Header/style.ts
  src/components/Layout/index.tsx
  src/components/Layout/style.ts
  src/components/Main/Common/IntroHeader/index.tsx
  src/components/Main/Common/IntroHeader/style.ts
  src/components/Main/Common/LocationCard/index.tsx
  src/components/Main/Common/LocationCard/style.ts
  src/components/Main/Common/LogoDescription/index.tsx
  src/components/Main/Common/LogoDescription/style.ts
  src/components/Main/Common/VeganDescription/index.tsx
  src/components/Main/Common/VeganDescription/style.ts
  src/components/Main/Common/WayToCome/index.tsx
  src/components/Main/Common/WayToCome/style.ts
  src/components/Main/DeskTop/Intro/index.tsx
  src/components/Main/DeskTop/Intro/style.ts
  src/components/Main/DeskTop/NewProduct/index.tsx
  src/components/Main/DeskTop/NewProduct/style.ts
  src/components/Main/DeskTop/PreviewGift/index.tsx
  src/components/Main/DeskTop/PreviewGift/style.ts
  src/components/Main/DeskTop/PreviewInsta/index.tsx
  src/components/Main/DeskTop/PreviewInsta/style.ts
  src/components/Swiper/index.tsx
  src/components/Swiper/style.ts
  src/constants/importImage.ts
  src/pages/Home/index.tsx
  src/pages/Intro/index.tsx
  src/stores/screenSizeStore.ts
Labels: ⚙️ chore, 💫 feat, ♻️ refactor, 🟦 typescript, 🧑🏻‍🎨 UI

#27 파일 경로 변경 및 swiper props 구현
  public/Main/Gift/크라프트사각박스.jpg
  src/App.css
  src/components/Common/FullPageScroll/style.ts
  src/components/Footer/style.ts
  src/components/GiftForm/index.tsx
  src/components/GiftItemList/index.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Intro/IntroHeader/index.tsx
  src/components/Intro/IntroHeader/style.ts
  src/components/Intro/LocationCard/index.tsx
  src/components/Intro/LocationCard/style.ts
  src/components/Intro/LogoDescription/index.tsx
  src/components/Intro/LogoDescription/style.ts
  src/components/Intro/VeganDescription/index.tsx
  src/components/Intro/VeganDescription/style.ts
  src/components/Intro/WayToCome/index.tsx
  src/components/Intro/WayToCome/style.ts
  src/components/Main/DeskTop/Intro/index.tsx
  src/components/Main/DeskTop/Intro/style.ts
  src/components/Main/DeskTop/NewProduct/index.tsx
  src/components/Main/DeskTop/PreviewGift/index.tsx
  src/components/Main/DeskTop/PreviewGift/style.ts
  src/components/Main/DeskTop/PreviewInsta/index.tsx
  src/components/Swiper/index.tsx
  src/components/Swiper/style.ts
  src/font/Alata.ttf
  src/font/Catamaran.ttf
  src/font/Jua.ttf
  src/font/LilitaOne.ttf
  src/font/font.css
  src/pages/Home/index.tsx
  src/pages/Intro/index.tsx
  src/styles/theme.ts
  src/types/swiper.ts
Labels: 📝 docs, 💫 feat, ♻️ refactor, 🟦 typescript, 🧑🏻‍🎨 UI
